package com.carbonflow.recovery;

import java.nio.file.Path;
import java.util.UUID;

/**
 * Recognises a CarbonFlow recovery-set directory.
 *
 * <p>Recovery sets are named with the UUIDv4 generated by REC-03. Both REC-07
 * (retention) and REC-08 (monitoring) need to tell a set this tool created from
 * an unrelated sibling directory, so the rule lives in one place rather than
 * being reimplemented — two subtly different copies of "is this a set?" would
 * eventually disagree about which directory is safe to delete.
 *
 * <p>Requiring the exact canonical form means a human's notes folder, a
 * {@code temp} directory, or a neighbouring project sharing the parent are all
 * treated as foreign.
 */
public final class RecoverySetNaming {

    private RecoverySetNaming() {
    }

    /** {@code true} when the directory name is a canonical UUIDv4 set identifier. */
    public static boolean isBackupSetDirectory(Path directory) {
        if (directory == null) {
            return false;
        }
        Path fileName = directory.getFileName();
        if (fileName == null) {
            return false;
        }
        String name = fileName.toString();
        if (name.length() != 36) {
            return false;
        }
        try {
            // UUID.fromString is lenient about group lengths, so re-render and
            // compare: only 8-4-4-4-12 is accepted.
            return UUID.fromString(name).toString().equalsIgnoreCase(name);
        } catch (IllegalArgumentException e) {
            return false;
        }
    }
}