package com.carbonflow.recovery.notify;

import java.time.Duration;
import java.time.Instant;
import java.util.Locale;
import java.util.regex.Pattern;

/**
 * A single operator-facing recovery notification.
 *
 * <h2>What a notification must contain</h2>
 * <p>Enough for an operator to act without opening a log: which control, what
 * happened, which backup or drill, when, how serious, and what to do next. A
 * message that says only "backup failed" is not actionable at 03:00.
 *
 * <h2>What a notification must never contain</h2>
 * <p>No password, token, key, credential, or evidence content. Every field is
 * either an enum, a timestamp, an identifier generated by this codebase, or a
 * short operator instruction — so a secret cannot reach a notification even by
 * accident, and {@link #toMessage()} additionally redacts anything that looks
 * like a credential before the text leaves this class.
 *
 * @param severity  how urgent the condition is
 * @param control   which recovery control raised it
 * @param event     the specific condition
 * @param severityDetail human-readable summary
 * @param subjectId backup set or drill identifier, or {@code null}
 * @param at        when it was observed (UTC)
 * @param state     the current state, as a short token
 * @param action    the recommended operator action
 */
public record RecoveryNotification(Severity severity, Control control, Event event,
                                   String detail, String subjectId, Instant at,
                                   String state, String action) {

    /** How urgent. Ordered so a caller can filter on severity. */
    public enum Severity {
        /** Informational; nothing is wrong. */
        INFO,
        /** Degraded but still inside the objective. */
        WARNING,
        /** The objective or the control has failed. */
        CRITICAL
    }

    /** Which recovery control raised the notification. */
    public enum Control {
        RECOVERY_BACKUP("Recovery backup"),
        RECOVERY_VERIFICATION("Backup verification"),
        RECOVERY_MONITORING("Backup monitoring"),
        RECOVERY_ENCRYPTION("Backup encryption"),
        RECOVERY_DRILL("Recovery drill"),
        RECOVERY_RETENTION("Backup retention");

        private final String label;

        Control(String label) {
            this.label = label;
        }

        public String label() {
            return label;
        }
    }

    /** The specific condition. */
    public enum Event {
        BACKUP_FAILED("Backup failed"),
        VERIFICATION_FAILED("Verification failed"),
        BACKUP_STALE("Backup is stale"),
        RPO_AT_RISK("RPO window at risk"),
        BACKUP_MISSING("No backup set exists"),
        BACKUP_UNVERIFIABLE("Backup could not be verified"),
        ENCRYPTION_FAILED("Encryption failed"),
        DRILL_FAILED("Recovery drill failed"),
        DRILL_OVERDUE("Recovery drill overdue"),
        DRILL_NOT_EXECUTABLE("Recovery drill not executable"),
        RETENTION_FAILURE("Retention did not run");

        private final String label;

        Event(String label) {
            this.label = label;
        }

        public String label() {
            return label;
        }
    }

    /**
     * Deduplication key for an unresolved condition.
     *
     * <p>Control plus event, deliberately excluding the subject id and the
     * timestamp: the same condition recurring for the same backup is one problem,
     * not several. A new backup set is a new condition and must alert again,
     * which is why the key is cleared when the condition resolves rather than
     * silently accumulating keys.
     */
    public String dedupKey() {
        return control.name() + "/" + event.name();
    }

    public RecoveryNotification {
        if (severity == null || control == null || event == null) {
            throw new IllegalArgumentException(
                    "severity, control and event are required");
        }
        if (at == null) {
            throw new IllegalArgumentException("at is required");
        }
        if (action == null || action.isBlank()) {
            // A notification without a recommended action is a log line, not an
            // operator notification.
            throw new IllegalArgumentException(
                    "an operator notification must carry a recommended action");
        }
    }

    /**
     * The rendered notification.
     *
     * <p>Every field is passed through {@link Redactor#redact(String)} on the way
     * out, so a value that reached a notification by some future code path cannot
     * leak a credential through a log or a status file.
     */
    public String toMessage() {
        StringBuilder message = new StringBuilder();
        message.append("[CARBONFLOW] ")
                .append(severity).append(" · ")
                .append(control.label()).append(" · ")
                .append(event.label());
        if (detail != null && !detail.isBlank()) {
            message.append(" — ").append(detail);
        }
        message.append("\n  subject : ")
                .append(subjectId == null ? "n/a" : subjectId);
        message.append("\n  at      : ").append(at);
        message.append("\n  state   : ").append(state == null ? "n/a" : state);
        message.append("\n  action  : ").append(action);
        return Redactor.redact(message.toString());
    }

    /** Machine-readable rendering. */
    public String toJson() {
        return "{\"severity\":\"" + severity + "\""
                + ",\"control\":\"" + control.name() + "\""
                + ",\"event\":\"" + event.name() + "\""
                + ",\"subjectId\":" + (subjectId == null ? "null"
                        : "\"" + Redactor.redact(subjectId) + "\"")
                + ",\"at\":\"" + at + "\""
                + ",\"state\":" + (state == null ? "null"
                        : "\"" + Redactor.redact(state) + "\"")
                + ",\"action\":\"" + Redactor.redact(action) + "\""
                + ",\"detail\":" + (detail == null ? "null"
                        : "\"" + Redactor.redact(detail) + "\"") + "}";
    }

    /** Patterns that look like credentials, redacted on the way out. */
    static final class Redactor {

        /**
         * Key=value or key: value pairs whose name suggests a credential.
         *
         * <p>Case-insensitive, and deliberately broad. A false positive costs a
         * notification a little of its detail; a false negative puts a live
         * secret into a log file and a status document.
         */
        private static final Pattern CREDENTIAL_ASSIGNMENT = Pattern.compile(
                "(?i)\\b([a-z0-9_.-]*(?:password|passwd|secret|token|credential|"
                        + "apikey|api_key|privatekey|private_key|passphrase|jwt|"
                        + "authorization|bearer)[a-z0-9_.-]*)(\\s*[:=]\\s*)"
                        + "(\\S+)");

        /** PEM block headers, redacted whole. */
        private static final Pattern PEM_HEADER = Pattern.compile(
                "(?s)-----BEGIN [A-Z ]*PRIVATE KEY-----.*?-----END [A-Z ]*PRIVATE KEY-----");

        /**
         * Header-style credentials, redacted to the end of the line.
         *
         * <p>Necessary because the single-token assignment rule is not enough for
         * these. In {@code Authorization: Bearer eyJ...} the scheme word is not
         * the secret — the token after it is — so redacting only the next
         * whitespace-delimited token would have left a live JWT in a log line.
         * Found by a test asserting the token is absent, not merely redacted.
         */
        private static final Pattern CREDENTIAL_HEADER = Pattern.compile(
                "(?i)\\b(authorization|proxy-authorization)\\s*[:=]\\s*[^\\n\\r]*");

        /** A bare bearer token, with no header name in front of it. */
        private static final Pattern BEARER_TOKEN = Pattern.compile(
                "(?i)\\bbearer\\s+[A-Za-z0-9._~+/=-]+");

        private Redactor() {
        }

        /** Replaces credential-looking values with a placeholder. */
        public static String redact(String input) {
            if (input == null) {
                return null;
            }
            String result = PEM_HEADER.matcher(input)
                    .replaceAll("[REDACTED PRIVATE KEY]");
            // Header and bearer forms first: they consume more text, so running
            // them before the single-token rule prevents the token rule from
            // preserving the secret.
            result = CREDENTIAL_HEADER.matcher(result)
                    .replaceAll(matchResult -> matchResult.group(1) + ": [REDACTED]");
            result = BEARER_TOKEN.matcher(result)
                    .replaceAll("Bearer [REDACTED]");
            result = CREDENTIAL_ASSIGNMENT.matcher(result)
                    .replaceAll(matchResult ->
                            matchResult.group(1) + matchResult.group(2) + "[REDACTED]");
            return result;
        }
    }

    /** Suppresses a notification for a repeat interval. */
    public static Duration defaultRepeatInterval() {
        // Long enough that a persistent outage does not page repeatedly, short
        // enough that a still-broken condition is not forgotten about.
        return Duration.ofHours(1);
    }

    /** Lowercase, stable token for a state, safe to include in a message. */
    public static String token(String state) {
        return state == null ? "UNKNOWN"
                : state.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9_]+", "_");
    }
}