/**
 * CarbonFlow — Canonical Role-Based Access Control (RBAC)
 */
import { RoleName, PermissionCode } from './types.ts';

export const ROLE_PERMISSIONS: Record<RoleName, PermissionCode[]> = {
  COMPANY_ADMIN: [
    'organization.read',
    'organization.update',
    'users.read',
    'users.create',
    'users.update',
    'users.disable',
    'facilities.read',
    'facilities.create',
    'facilities.update',
    'facilities.delete',
    'reporting_periods.read',
    'reporting_periods.create',
    'reporting_periods.update',
    'activity_data.read',
    'activity_data.create',
    'activity_data.update',
    'activity_data.submit',
    'emission_factors.read',
    'emission_factors.manage',
    'calculations.read',
    'calculations.create',
    'evidence.read',
    'evidence.upload',
    'evidence.delete',
    'evidence.version',
    'audits.read',
    'audits.create',
    'audits.submit',
    'audits.approve',
    'audits.lock',
    'inventory.read',
    'inventory.create',
    'inventory.lock',
    'targets.read',
    'targets.create',
    'targets.update',
    'reduction_projects.read',
    'reduction_projects.create',
    'reduction_projects.update',
    'reports.read',
    'analytics.read',
  ],

  SUSTAINABILITY_MANAGER: [
    'organization.read',
    'users.read',
    'facilities.read',
    'facilities.create',
    'facilities.update',
    'reporting_periods.read',
    'reporting_periods.create',
    'reporting_periods.update',
    'activity_data.read',
    'activity_data.create',
    'activity_data.update',
    'activity_data.submit',
    'emission_factors.read',
    'emission_factors.manage',
    'calculations.read',
    'calculations.create',
    'evidence.read',
    'evidence.upload',
    'evidence.delete',
    'evidence.version',
    'audits.read',
    'audits.create',
    'audits.submit',
    'audits.approve',
    'audits.lock',
    'inventory.read',
    'inventory.create',
    'inventory.lock',
    'targets.read',
    'targets.create',
    'targets.update',
    'reduction_projects.read',
    'reduction_projects.create',
    'reduction_projects.update',
    'reports.read',
    'analytics.read',
  ],

  CARBON_ACCOUNTANT: [
    'organization.read',
    'facilities.read',
    'reporting_periods.read',
    'activity_data.read',
    'activity_data.create',
    'activity_data.update',
    'activity_data.submit',
    'emission_factors.read',
    'emission_factors.manage',
    'calculations.read',
    'calculations.create',
    'evidence.read',
    'evidence.upload',
    'evidence.version',
    'audits.read',
    'inventory.read',
    'inventory.create',
    'targets.read',
    'targets.update',
    'reduction_projects.read',
    'reduction_projects.update',
    'reports.read',
    'analytics.read',
  ],

  DATA_OWNER: [
    'organization.read',
    'facilities.read',
    'reporting_periods.read',
    'activity_data.read',
    'activity_data.create',
    'activity_data.update',
    'activity_data.submit',
    'emission_factors.read',
    'evidence.read',
    'evidence.upload',
    'evidence.version',
    'targets.read',
    'reduction_projects.read',
    'analytics.read',
  ],

  FACILITY_MANAGER: [
    'organization.read',
    'facilities.read',
    'facilities.update',
    'reporting_periods.read',
    'activity_data.read',
    'activity_data.create',
    'activity_data.update',
    'activity_data.submit',
    'emission_factors.read',
    'evidence.read',
    'evidence.upload',
    'targets.read',
    'reduction_projects.read',
    'reduction_projects.update',
    'analytics.read',
  ],

  REVIEWER: [
    'organization.read',
    'facilities.read',
    'reporting_periods.read',
    'activity_data.read',
    'emission_factors.read',
    'calculations.read',
    'evidence.read',
    'audits.read',
    'audits.review',
    'audits.approve',
    'inventory.read',
    'targets.read',
    'reduction_projects.read',
    'reports.read',
    'analytics.read',
  ],

  MANAGEMENT: [
    'organization.read',
    'facilities.read',
    'reporting_periods.read',
    'activity_data.read',
    'emission_factors.read',
    'calculations.read',
    'evidence.read',
    'audits.read',
    'inventory.read',
    'targets.read',
    'reduction_projects.read',
    'reports.read',
    'analytics.read',
  ],

  ASSURANCE_PROVIDER: [
    'organization.read',
    'facilities.read',
    'reporting_periods.read',
    'activity_data.read',
    'emission_factors.read',
    'calculations.read',
    'evidence.read',
    'audits.read',
    'audits.review',
    'inventory.read',
    'targets.read',
    'reduction_projects.read',
    'reports.read',
    'analytics.read',
  ],

  PLATFORM_ADMIN: [
    'users.read',
    'emission_factors.read',
    'emission_factors.manage',
    'platform.tenants.read',
    'platform.tenants.manage',
  ],
};

export function hasPermission(role: RoleName, permission: PermissionCode): boolean {
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
}
